---
apiVersion: v2
name: azimuth-capi-operator
description: Helm chart for deploying the Azimuth CAPI operator.
type: application
# The version and appVersion are updated by the chart build script
version: 0.1.0
appVersion: main

dependencies:
  # stakater/reloader to reload when certificates change
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 1.0.101
    condition: reloader.enabled
  # prometheus-community/kube-state-metrics to produce metrics on clusters
  - name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 5.19.1
    alias: metrics
    condition: metrics.enabled
