---

version: 2

updates:
  # Automatically propose PRs for Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"

