apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
subjects:
  # Target the service account in the release namespace
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "azimuth-capi-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "azimuth-capi-operator.fullname" . }}
