apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - clustertemplates.azimuth.stackhpc.com
      - clusters.azimuth.stackhpc.com
    verbs:
      - update
      - patch
  - apiGroups:
      - azimuth.stackhpc.com
    resources:
      - clustertemplates
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - azimuth.stackhpc.com
    resources:
      - clusters
    verbs:
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - azimuth.stackhpc.com
    resources:
      - clusters/status
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
      - machinedeployments
      - machines
      - machinehealthchecks
    verbs:
      - "*"
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    resources:
      - kubeadmconfigtemplates
    verbs:
      - "*"
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    resources:
      - kubeadmcontrolplanes
    verbs:
      - "*"
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - openstackclusters
      - openstackmachinetemplates
    verbs:
      - "*"
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - openstackmachines
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - addons.stackhpc.com
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
