apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
rules:
  # Manipulating CRDs (only allow patching of our own CRDs)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - clustertemplates.azimuth.stackhpc.com
      - clusters.azimuth.stackhpc.com
      - apptemplates.azimuth.stackhpc.com
    verbs:
      - update
      - patch
  # Required for kopf to watch resources properly
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  # Required for kopf to produce events properly
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  # We can manipulate our own objects
  - apiGroups:
      - azimuth.stackhpc.com
    resources:
      - "*"
    verbs:
      - "*"
  # We need to be able to manipulate secrets
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
  # We need to be able to query Cluster API objects
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
      - machinedeployments
      - machines
      - machinehealthchecks
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    resources:
      - kubeadmconfigtemplates
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    resources:
      - kubeadmcontrolplanes
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - openstackclusters
      - openstackmachinetemplates
      - openstackmachines
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - addons.stackhpc.com
    resources:
      - helmreleases
      - manifests
    verbs:
      - list
      - get
      - watch
