apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
  annotations:
    # Trigger a rollout when the certificate changes
    secret.reloader.stakater.com/reload: {{ include "azimuth-capi-operator.fullname" . }}-cert
spec:
  # Allow only one replica at once with the recreate strategy in order to avoid races
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "azimuth-capi-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "azimuth-capi-operator.selectorLabels" . | nindent 8 }}
      annotations:
        # Force the deployment to roll when the config changes
        azimuth.stackhpc.com/config-hash: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "azimuth-capi-operator.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: webhook
              containerPort: 8443
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: etc-azimuth
              mountPath: /etc/azimuth
              readOnly: true
            - name: etc-azimuth-cert
              mountPath: /etc/azimuth/cert
              readOnly: true
            - name: tmp
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: etc-azimuth
          secret:
            secretName: {{ include "azimuth-capi-operator.fullname" . }}
        - name: etc-azimuth-cert
          secret:
            secretName: {{ include "azimuth-capi-operator.fullname" . }}-cert
        - name: tmp
          emptyDir: {}
