apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
spec:
  # Allow only one replica at once with the recreate strategy in order to avoid races
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "azimuth-capi-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "azimuth-capi-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "azimuth-capi-operator.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
        # The operator delegates Kubernetes authentication to "kubectl proxy"
        - name: kubectl-proxy
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          {{- $vn := semver .Capabilities.KubeVersion.Version }}
          {{- $defaultTag := printf "%d.%d.%d" $vn.Major $vn.Minor $vn.Patch }}
          image: {{ printf "%s:%s" .Values.kubectlProxy.image.repository (default $defaultTag .Values.kubectlProxy.image.tag) }}
          imagePullPolicy: {{ .Values.kubectlProxy.image.pullPolicy }}
          args: [proxy]
          resources: {{ toYaml .Values.kubectlProxy.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
