apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
