apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
stringData:
  # As the entrypoint, just include all other YAML files in /etc/azimuth
  capi-operator.yaml: |
    !include "/etc/azimuth/*.yaml,!/etc/azimuth/capi-operator.yaml"
  # Install the values from the config into another file
  # Make sure that they override all options specified in other files by
  # using a prefix that comes late in the sort order
  zz-user-config.yaml: {{ tpl (toYaml .Values.config) . | nindent 4 }}
