apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
stringData:
  capi-operator.yaml: {{ tpl (toYaml .Values.config) . | nindent 4 }}
