{
 "title": "Azimuth / Kubernetes clusters",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Clusters Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_template) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name)) by(phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by namespace",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_template) by(cluster_namespace, cluster_name)) by(cluster_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_phase{phase=\"Ready\"}) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_phase{phase=~\"Unhealthy|Failed|Unknown\"}) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster version",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_kube_version) by(cluster_namespace, cluster_name)) by(kube_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control plane phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_control_plane_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name)) by(phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready control planes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_control_plane_phase{phase=\"Ready\"}) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy control planes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_control_plane_phase{phase=~\"Unhealthy|Failed|Unknown\"}) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name, node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name, node)) by(phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node kubelet version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_kubelet_version) by(cluster_namespace, cluster_name, node)) by(kubelet_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_phase{phase=\"Ready\"}) by(cluster_namespace, cluster_name, node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_phase{phase=~\"Unhealthy|Failed|Unknown\"}) by(cluster_namespace, cluster_name, node))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Addons Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_addon_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name, addon))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addon phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_addon_phase{phase=~\".+\"}) by(cluster_namespace, cluster_name, addon)) by(phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_addon_phase{phase=\"Deployed\"}) by(cluster_namespace, cluster_name, addon))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_node_phase{phase=~\"Failed|Unknown\"}) by(cluster_namespace, cluster_name, addon))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Templates Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cluster templates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_clustertemplate_kube_version) by(template_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by template",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_template) by(cluster_namespace, cluster_name)) by(template)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters using deprecated templates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_template * on(instance, template) group_left() label_replace(azimuth_kube_clustertemplate_deprecated, \"template\", \"$1\", \"template_name\", \"(.+)\")) by(cluster_namespace, cluster_name)) by(template)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deprecated templates",
   "type": "stat",
   "description": "Number of cluster templates that are marked as deprecated.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_clustertemplate_deprecated) by(template_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deprecated clusters",
   "type": "stat",
   "description": "Number of clusters that are using a deprecated template.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_kube_cluster_template * on(instance, template) group_left() label_replace(azimuth_kube_clustertemplate_deprecated, \"template\", \"$1\", \"template_name\", \"(.+)\")) by(cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Template Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Templates",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "topk(1, azimuth_kube_clustertemplate_kube_version * on(instance, template_name) group_left() azimuth_kube_clustertemplate_deprecated) by(template_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(count(topk(1, azimuth_kube_cluster_template) by(cluster_namespace, cluster_name)) by(template), \"template_name\", \"$1\", \"template\", \"(.+)\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "label_join(topk(1, azimuth_kube_cluster_template * on(instance, cluster_namespace, cluster_name) group_left(kube_version) azimuth_kube_cluster_kube_version * on(instance, cluster_namespace, cluster_name) group_left(phase) azimuth_kube_cluster_phase * on(instance, cluster_namespace, cluster_name) group_left(networking_phase) label_replace(azimuth_kube_cluster_networking_phase, \"networking_phase\", \"$1\", \"phase\", \"(.+)\") * on(instance, cluster_namespace, cluster_name) group_left(control_plane_phase) label_replace(azimuth_kube_cluster_control_plane_phase, \"control_plane_phase\", \"$1\", \"phase\", \"(.+)\")) by(cluster_namespace, cluster_name), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(topk(1, azimuth_kube_cluster_node_count) by(cluster_namespace, cluster_name), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(topk(1, azimuth_kube_cluster_addon_count) by(cluster_namespace, cluster_name), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(topk(1, label_replace(azimuth_kube_cluster_template, \"template_name\", \"$1\", \"template\", \"(.+)\") * on(instance, template_name) group_left() azimuth_kube_clustertemplate_deprecated) by(cluster_namespace, cluster_name), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "label_join(topk(1, azimuth_kube_cluster_node_phase * on(instance, cluster_namespace, cluster_name, node) group_left(kubelet_version) azimuth_kube_cluster_node_kubelet_version) by(cluster_namespace, cluster_name, node), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Addon Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Addons",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "label_join(topk(1, azimuth_kube_cluster_addon_phase) by(cluster_namespace, cluster_name, addon), \"cluster\", \"/\", \"cluster_namespace\", \"cluster_name\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}