{
 "title": "Azimuth / Kubernetes clusters",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Clusters Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_template) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (azimuth_kube_cluster_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Networking phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (azimuth_kube_cluster_networking_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_phase{phase=\"Ready\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_phase{phase=~\"Unhealthy|Failed|Unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster version",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kube_version) (azimuth_kube_cluster_kube_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control plane phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (azimuth_kube_cluster_control_plane_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready control planes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_control_plane_phase{phase=\"Ready\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy control planes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_control_plane_phase{phase=~\"Unhealthy|Failed|Unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_node_phase) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (azimuth_kube_cluster_node_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node kubelet version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kubelet_version) (azimuth_kube_cluster_node_kubelet_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_node_phase{phase=\"Ready\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_node_phase{phase=~\"Unhealthy|Failed|Unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Addons overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_addon_phase) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addon phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase) (azimuth_kube_cluster_addon_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_addon_phase{phase=\"Deployed\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed addons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_node_phase{phase=~\"Failed|Unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster templates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cluster templates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_clustertemplate_kube_version) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App templates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(azimuth_kube_apptemplate_last_sync) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster template",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(template) (azimuth_kube_cluster_template)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters running deprecated templates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "sum by(template) (azimuth_kube_cluster_template * on(template) label_replace(azimuth_kube_clustertemplate_deprecated, \"template\", \"$1\", \"template_name\", \"(.+)\")) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deprecated cluster templates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_clustertemplate_deprecated) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters running deprecated templates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_kube_cluster_template * on(template) label_replace(azimuth_kube_clustertemplate_deprecated, \"template\", \"$1\", \"template_name\", \"(.+)\")) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}