cloudCredentialsSecretName: "{{ spec.cloud_credentials_secret_name }}"

{% if spec.external_network_id or spec.network_id %}
clusterNetworking:
{% if spec.external_network_id %}
  externalNetworkId: {{ spec.external_network_id }}
{% endif %}
{% if spec.network_id %}
  internalNetwork:
    networkFilter:
      id: {{ spec.network_id }}
{% endif %}
{% endif %}

controlPlane:
  machineFlavor: "{{ spec.control_plane_machine_size }}"
  healthCheck:
    enabled: {{ "true" if spec.autohealing else "false" }}

nodeGroupDefaults:
  healthCheck:
    enabled: {{ "true" if spec.autohealing else "false" }}

nodeGroups:
{% for node_group in spec.node_groups %}
  - name: "{{ node_group.name }}"
    machineFlavor: "{{ node_group.machine_size }}"
    autoscale: {{ "true" if node_group.autoscale else "false" }}
{% if node_group.autoscale %}
    machineCountMin: {{ node_group.min_count }}
    machineCountMax: {{ node_group.max_count }}
{% else %}
    machineCount: {{ node_group.count }}
{% endif %}
{% endfor %}

addons:
  kubernetesDashboard:
    enabled: {{ "true" if spec.addons.dashboard else "false" }}
  ingress:
    enabled: {{ "true" if spec.addons.ingress else "false" }}
  monitoring:
    enabled: {{ "true" if spec.addons.monitoring else "false" }}
