#!/usr/bin/env bash

# Wait for the kubectl proxy to become available
KUBE_PROXY_URL="${KUBE_PROXY_URL:-"http://127.0.0.1:8001"}"

until curl -fsSL "$KUBE_PROXY_URL/api" >/dev/null 2>&1; do
    sleep 1
done

# Run kopf with the operator module
exec kopf run --module azimuth_capi.operator "$@"
