---
name: Publish artifacts

on:
  # Publish artifacts on every push to main and every tag
  push:
    branches:
      - main
    tags:
      - "*"
  # Also allow publication to be done via a workflow call
  # In this case, the chart version is returned as an output
  workflow_call:
    inputs:
      ref:
        type: string
        description: The ref to build.
        required: true
    outputs:
      chart-version:
        description: The chart version that was published
        value: ${{ jobs.build_push_chart.outputs.chart-version }}

# Variables controlling the dependencies that are baked in to the image
env:
  HELM_VERSION: v3.13.2
  # CAPI Helm chart
  OPENSTACK_CLUSTER_CHART_REPO: https://stackhpc.github.io/capi-helm-charts
  OPENSTACK_CLUSTER_CHART_NAME: openstack-cluster
  OPENSTACK_CLUSTER_CHART_VERSION: 0.1.6
  # Zenith charts
  ZENITH_CHART_REPO: https://stackhpc.github.io/zenith
  ZENITH_CHART_VERSION: 0.2.0-rc.1
  ZENITH_APISERVER_CHART_NAME: zenith-apiserver
  ZENITH_OPERATOR_CHART_NAME: zenith-operator

jobs:
  build_push_images:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/stackhpc/azimuth-capi-operator
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: stackhpc/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: azimuth-capi-operator
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            HELM_VERSION=${{ env.HELM_VERSION }}
            OPENSTACK_CLUSTER_CHART_REPO=${{ env.OPENSTACK_CLUSTER_CHART_REPO }}
            OPENSTACK_CLUSTER_CHART_NAME=${{ env.OPENSTACK_CLUSTER_CHART_NAME }}
            OPENSTACK_CLUSTER_CHART_VERSION=${{ env.OPENSTACK_CLUSTER_CHART_VERSION }}
            ZENITH_CHART_REPO=${{ env.ZENITH_CHART_REPO }}
            ZENITH_CHART_VERSION=${{ env.ZENITH_CHART_VERSION }}
            ZENITH_APISERVER_CHART_NAME=${{ env.ZENITH_APISERVER_CHART_NAME }}
            ZENITH_OPERATOR_CHART_NAME=${{ env.ZENITH_OPERATOR_CHART_NAME }}
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}

  build_push_chart:
    name: Build and push Helm chart
    runs-on: ubuntu-latest
    # Only build and push the chart if the images built successfully
    needs: [build_push_images]
    outputs:
      chart-version: ${{ steps.semver.outputs.version }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          # This is important for the semver action to work correctly
          # when determining the number of commits since the last tag
          fetch-depth: 0

      - name: Get SemVer version for current commit
        id: semver
        uses: stackhpc/github-actions/semver@master

      - name: Publish Helm charts
        uses: stackhpc/github-actions/helm-publish@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.semver.outputs.version }}
          app-version: ${{ steps.semver.outputs.short-sha }}
